### ISSUE TITLE
Main branch not synced with the recent updates

### ISSUE THREAD

**Issue by NajtexQ** [luxonis/depthai-nodes#80]
Missing xfeat parser update.

**Comment by klemen1999** [comment]
Hi @NajtexQ , this library is currently in an alpha stage and we are actively developing it. We keep main branch reserved for stable releases whereas new features are getting incrementally added to other branches. For `XFeat` specifically there is currently updated version on `feature/xfeat` branch which has option to trigger it and also option to work on two inputs (e.g. left and right camera). CC: @kkeroo for additional information if needed

**Comment by Erol444** [comment]
@klemen1999 when can we mainline it, so we can prepare blog post about it?

**Comment by klemen1999** [comment]
@Erol444 Initial plan was to wait for the "ParserV2" refactoring and then make a new release - this will introduce some breaking changes. On the other hand there are some models (OCR, Lane detection, some other fixes) which now have parsers only in `dev` branch. So we can make a release for this and then make a bigger release once refactoring is finished. 
For the blog though IMO it is valuable to wait for the "ParsersV2" just because of the changes in the API. After that release the overall structure should stay roughly the same going forward.

**Comment by klemen1999** [comment]
Hi @NajtexQ 
We've made a new release, [v0.0.2-alpha](https://github.com/luxonis/depthai-nodes/releases/tag/v0.0.2-alpha), that includes the XFeat parser along with some other smaller bugfixes and changes. Feel free to check it out.
